### ISSUE TITLE
Changes to `mod` functionality

### ISSUE THREAD

**Issue by binaek** [turbot/steampipe#3323]
# `mod.sp`
- [x] `steampipe` constraint in the `require` block should be an unnamed block [#3343]

Current (deprecate):
```hcl
require {
  steampipe  = "0.10.0"
}
```
proposed
```hcl
require {
  steampipe {
    min_version = "0.10.0"
  }
}
```

- [x] deprecate the `version` argument, and replace it with `min_version` in `require.plugin` [#3343]

Current (deprecate):
```hcl
  require {
    plugin "aws"{
      version = "0.86"
    }
  }
```
Proposed
```hcl
  require {
    plugin "aws"{
      min_version = "0.86"
    }
  }
```

- [x] #3276 
- [x] #3324
- [x] #3346 
- [x] #3349 
- [x] #3325
- [x] #3041 
- [x] #3279 
- [x] #3359
- [x] #3363 
- [x] #3429 
- [x] Deprecation plan https://github.com/turbot/steampipe/issues/3323#issuecomment-1550797786

**Comment by pskrbasu** [comment]
Mod require `version` --> `min_version` deprecation plan(possible):

- Week 0: Support both in v0.20.0
- Week ~4: Update mods to use min_version, with min v0.20.0 req
- Week ~6: Add deprecation warning in v0.21.0, but continue to support version
- Week ~12: Remove version in v0.22.0
