### ISSUE TITLE
Refactor/Update code structure

### ISSUE THREAD

**Issue by pskrbasu** [turbot/steampipe#3764]
#### This issue tracks all refactor and code structure related issues:

- [ ] https://github.com/turbot/steampipe/issues/1278
- [ ] https://github.com/turbot/steampipe/issues/1327
- [ ] https://github.com/turbot/steampipe/issues/1624
- [ ] https://github.com/turbot/steampipe/issues/2371
- [ ] https://github.com/turbot/steampipe/issues/2037
- [ ] https://github.com/turbot/steampipe/issues/1936
- [ ] https://github.com/turbot/steampipe/issues/1394
- [ ] https://github.com/turbot/steampipe/issues/1218
